### PR TITLE
Update to support compose-multiplatform 1.7.0-beta02

### PR DESCRIPTION
**Pull request by schott12521**
- There was a bug that was causing this library to crash when using the newer compose library
- Also applied some general code clean
- Refactored build.gradle.kts to only build the library by default, resulting in much faster builds, as the example can be built independently
- Removed nexus / maven publishing from the build step, as this should be taken care of ideally by a github action that only operates on commits to the master branch
- Removed unused imports -> Ideally optimize imports should be on by default for this repo
- Enabled parallel gradle builds
- Tested on iOS / Android devices and simulators!
- Version bump to `0.2.0-alpha05`

### CODE REVIEW

**Comment by alexzhirkevich** [comment]
There are a few issues.
- Icons are autogenerated and should not be modified 
- Automatic IDE cleanups for a whole codebase are not acceptable as they remove a lot of stuff that is important.
- Compose 1.7 beta has many critical bugs and cannot be used right now. It will also make the library incompatible with stable Compose 1.6

And it is hard to review 10k diff 1700 changed files PRs. Ideally only changes related to 1.7 compilation should be included in such a PR. I can't even leave a review, it crashes my browser, only comment here

**Comment by schott12521** [comment]
Fair enough, I would loathe seeing a PR this big.

I'll make another PR that includes only the small changes necessary for compose 1.7.0, which went into RC-01 today so I think the bugs are probably getting worked out and it's worth updating libraries.

Wouldn't those worried about breaking changes be able to depend on 0.1.0-alpha04 indefinitely?

**Comment by alexzhirkevich** [comment]
1.7 rc looks better

**Comment by schott12521** [comment]
Closing in favor of new/smaller PR: https://github.com/alexzhirkevich/compose-cupertino/pull/64

**Pull request closed without merging**
