### PR TITLE
Fix SystemBar content color before IOS 17

### LINKED ISSUE #18: SystemBarStyle: Content color IOS 16.7 is always white
On my test device (IPhone 8+, IOS 16.7) in the sample the content color of the StatusBar is always white.
I think you should try using the following code:

```kotlin
UIApplication.sharedApplication.setStatusBarStyle(
        if (isDark) UIStatusBarStyleLightContent else UIStatusBarStyleDarkContent
    )
viewController.setNeedsStatusBarAppearanceUpdate()
```

Screenshot of the problem:
image

### PR DESCRIPTION
**Pull request by Lavmee**
fix #18 

Result (1-2 sim, 3-4 real):
image
image
image
image

### CODE REVIEW

**Comment by alexzhirkevich** [comment]
Will it work like before on iOS 17 if you set light theme and full black screen?

**Comment by alexzhirkevich** [comment]
And could you also please check if it will work if you use this insted:
```kotlin
viewController.overrideUserInterfaceStyle = if (dark) 
    UIUserInterfaceStyle.UIUserInterfaceStyleDark 
else UIUserInterfaceStyle.UIUserInterfaceStyleLight
```

It should work without plist property and set correct keyboard and nav strip appearance

**Comment by Lavmee** [comment]
i tried overrideUserInterfaceStyle but it doesn't work.

```kotlin
LaunchedEffect(dark) {
        viewController.overrideUserInterfaceStyle = if (dark)
            UIUserInterfaceStyle.UIUserInterfaceStyleDark
        else UIUserInterfaceStyle.UIUserInterfaceStyleLight
        viewController.setNeedsStatusBarAppearanceUpdate()
    }
```

**Comment by Lavmee** [comment]
> Will it work like before on iOS 17 if you set light theme and full black screen?

Yes, it works, the only problem I noticed is when opening bottomsheet with a light theme.

**Comment by alexzhirkevich** [comment]
Thanks! Status bar style for bottom sheet is complex because of different presentation styles and detents. I'll probably do it later

**Pull request merged**
